import { describe, expect, it } from 'vitest'
import { initialDetectorState, reduceGoal, type GoalSpec, type LessonEvent } from '../lessons/engine'
import type { ControlEvent, ControlKind } from '../midi/types'

const event = (kind: ControlKind, index: number, value = .8, ts = 0, on = true): ControlEvent => ({ kind, index, value, ts, on, channel: 0, source: 'demo' })
function run(goal: GoalSpec, events: LessonEvent[]) { let state = initialDetectorState(); let result = { state, progress: 0, done: false }; events.forEach((item) => { result = reduceGoal(goal, result.state, item) }); return result }
const noteStream = (notes: number[], intervalMs: number, start = 0) => notes.map((note, index) => event('key', note, .8, start + index * intervalMs))

describe('lesson goal detectors', () => {
  it('event matches kind, index, and velocity bounds', () => { const goal: GoalSpec = { type: 'event', match: { kind: 'pad', index: 2, minVelocity: .5 } }; expect(run(goal, [event('pad', 2, .4)]).done).toBe(false); expect(run(goal, [event('pad', 2, .7)]).done).toBe(true) })
  it('event matches note-range bounds for octave travel', () => { expect(run({ type: 'event', match: { kind: 'key', maxIndex: 44 } }, [event('key', 48), event('key', 43)]).done).toBe(true); expect(run({ type: 'event', match: { kind: 'key', minIndex: 76 } }, [event('key', 72), event('key', 75)]).done).toBe(false); expect(run({ type: 'event', match: { kind: 'key', minIndex: 76 } }, [event('key', 81)]).done).toBe(true) })
  it('event deviation matches movement away from the pitch-wheel center', () => { const goal: GoalSpec = { type: 'event', match: { kind: 'pitch', deviation: .15 } }; expect(run(goal, [event('pitch', 0, .5)]).done).toBe(false); expect(run(goal, [event('pitch', 0, .64)]).done).toBe(false); expect(run(goal, [event('pitch', 0, .66)]).done).toBe(true) })
  it('count advances only matching attacks', () => { const result = run({ type: 'count', match: { kind: 'key' }, n: 2 }, [event('pad', 0), event('key', 60), event('key', 60, 0, 2, false), event('key', 62)]); expect(result.done).toBe(true); expect(result.progress).toBe(1) })
  it('sweep tracks cumulative range, regardless of direction', () => { const result = run({ type: 'sweep', index: 1, span: .9 }, [event('knob', 1, .96), event('knob', 1, .04)]); expect(result.done).toBe(true) })
  it('sequence resets on a miss and accepts pitches in any octave', () => { const goal: GoalSpec = { type: 'notes', notes: [0, 2, 4], mode: 'sequence', anyOctave: true }; expect(run(goal, [event('key', 60), event('key', 62), event('key', 64)]).done).toBe(true); expect(run(goal, [event('key', 60), event('key', 63)]).progress).toBe(0) })
  it('chord requires all notes inside its time window', () => { const goal: GoalSpec = { type: 'notes', notes: [0, 4, 7], mode: 'chord', anyOctave: true, windowMs: 80 }; expect(run(goal, [event('key', 60, .7, 100), event('key', 64, .7, 150), event('key', 67, .7, 175)]).done).toBe(true); expect(run(goal, [event('key', 60, .7, 0), event('key', 64, .7, 100), event('key', 67, .7, 110)]).done).toBe(false) })
  it('timing counts only target-pad hits near requested beats', () => { const goal: GoalSpec = { type: 'timing', beats: [0, 2], padIndex: 0, bpm: 60, toleranceMs: 100, hits: 2 }; const result = run(goal, [event('pad', 0, 1, 30), event('pad', 0, 1, 2010)]); expect(result.done).toBe(true); expect(run(goal, [event('pad', 0, 1, 500)]).progress).toBe(0) })
  it('calibrate counts each pad or knob once', () => { const padEvents = Array.from({ length: 8 }, (_, i) => event('pad', i)); expect(run({ type: 'calibrate', target: 'pads' }, [padEvents[0]!, padEvents[0]!, ...padEvents.slice(1)]).done).toBe(true); const knobs = Array.from({ length: 8 }, (_, i) => event('knob', i)); expect(run({ type: 'calibrate', target: 'knobs' }, knobs).done).toBe(true) })
  it('pattern recognizes the taught kick, snare, and hat grid', () => { const grid = Array.from({ length: 8 }, () => Array(16).fill(false) as boolean[]); [0,8].forEach((i) => grid[0]![i] = true); [4,12].forEach((i) => grid[1]![i] = true); [0,2,4,6,8,10,12,14].forEach((i) => grid[2]![i] = true); expect(run({ type: 'pattern', check: 'firstBeat' }, [{ kind: 'pattern', grid, ts: 0 }]).done).toBe(true) })
  it('stream recognizes ten evenly spaced arp notes', () => { const notes = Array.from({ length: 10 }, (_, index) => 60 + index % 3 * 4); const result = run({ type: 'stream', n: 10, withinMs: 3000 }, noteStream(notes, 200)); expect(result.done).toBe(true); expect(result.progress).toBe(1) })
  it('stream rejects manual playing with 600ms gaps', () => { const notes = Array.from({ length: 10 }, (_, index) => 60 + index % 3 * 4); expect(run({ type: 'stream', n: 10, withinMs: 6000 }, noteStream(notes, 600)).done).toBe(false) })
  it('stream rejects a 20ms glissando', () => { const notes = Array.from({ length: 10 }, (_, index) => 60 + index); expect(run({ type: 'stream', n: 10, withinMs: 3000 }, noteStream(notes, 20)).done).toBe(false) })
  it('stream enforces its minimum pitch span', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 3000, minSpan: 13 }; expect(run(goal, noteStream([60, 64, 76, 60, 64, 76, 60, 64, 76, 60], 200)).done).toBe(true); expect(run(goal, noteStream([60, 64, 67, 60, 64, 67, 60, 64, 67, 60], 200)).done).toBe(false) })
  it('stream detects descending direction and rejects ascending motion', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 3000, direction: 'down' }; expect(run(goal, noteStream([72, 71, 70, 69, 68, 67, 66, 65, 64, 63], 200)).done).toBe(true); expect(run(goal, noteStream([60, 61, 62, 63, 64, 65, 66, 67, 68, 69], 200)).done).toBe(false) })
  it('stream direction accepts a real DOWN arp cycling a 3-note chord (2/3 pairs descend)', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 4000, direction: 'down' }; expect(run(goal, noteStream([67, 64, 60, 67, 64, 60, 67, 64, 60, 67, 64, 60], 250)).done).toBe(true) })
  it('stream direction rejects an UP arp cycling a 3-note chord', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 4000, direction: 'down' }; expect(run(goal, noteStream([60, 64, 67, 60, 64, 67, 60, 64, 67, 60, 64, 67], 250)).done).toBe(false) })
  it('stream density requires a later valid window at least 1.6x faster', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 3000, denser: true }; const baseline = noteStream(Array.from({ length: 10 }, (_, index) => 60 + index % 3 * 4), 200); const faster = noteStream(Array.from({ length: 20 }, (_, index) => 60 + index % 3 * 4), 100, 3200); const result = run(goal, [...baseline, ...faster]); expect(result.state.baselineMedian).toBe(200); expect(result.done).toBe(true) })

  it('chordmode recognizes a single tight triad', () => { const result = run({ type: 'chordmode', minClusters: 1, minVoices: 3 }, [event('key', 60, .8, 100), event('key', 64, .8, 105), event('key', 67, .8, 110)]); expect(result.done).toBe(true); expect(result.progress).toBe(1) })
  it('chordmode recognizes a three-chord progression with root span', () => { const goal: GoalSpec = { type: 'chordmode', minClusters: 3, minVoices: 3, rootSpan: 4 }; const chordAt = (root: number, start: number) => [root, root + 4, root + 7].map((note, index) => event('key', note, .8, start + index * 5)); const events = [...chordAt(60, 0), ...chordAt(62, 300), ...chordAt(64, 600)]; expect(run(goal, events).done).toBe(true) })
  it('chordmode rejects a human-spread triad', () => { const result = run({ type: 'chordmode', minClusters: 1, minVoices: 3 }, [event('key', 60, .8, 0), event('key', 64, .8, 60), event('key', 67, .8, 130)]); expect(result.done).toBe(false); expect(result.progress).toBe(0) })
  it('chordmode caps progress when clusters repeat the same root and miss the span', () => { const goal: GoalSpec = { type: 'chordmode', minClusters: 3, minVoices: 3, rootSpan: 4 }; const chordAt = (start: number) => [60, 64, 67].map((note, index) => event('key', note, .8, start + index * 5)); const events = [...chordAt(0), ...chordAt(400), ...chordAt(800)]; const result = run(goal, events); expect(result.done).toBe(false); expect(result.progress).toBeLessThanOrEqual(.8) })

  it('scalefit recognizes a two-octave major sweep', () => { const notes = [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84]; expect(run({ type: 'scalefit', minNotes: 10, minSpan: 12, maxClasses: 8 }, noteStream(notes, 200)).done).toBe(true) })
  it('scalefit rejects a chromatic sweep and caps its progress', () => { const notes = Array.from({ length: 25 }, (_, index) => 60 + index); const result = run({ type: 'scalefit', minNotes: 10, minSpan: 12, maxClasses: 8 }, noteStream(notes, 200)); expect(result.done).toBe(false); expect(result.progress).toBeLessThanOrEqual(.8) })
  it('scalefit recognizes a minor-pentatonic sweep', () => { const notes = [60, 63, 65, 67, 70, 72, 75, 77, 79, 82]; expect(run({ type: 'scalefit', minNotes: 10, minSpan: 12, maxClasses: 8 }, noteStream(notes, 200)).done).toBe(true) })
  it('scalefit reports partial progress for a short, narrow run', () => { const result = run({ type: 'scalefit', minNotes: 10, minSpan: 12, maxClasses: 8 }, noteStream([60, 62, 64], 200)); expect(result.done).toBe(false); expect(result.progress).toBeCloseTo(.21) })

  it('repeat recognizes ten evenly spaced pad hits', () => { const events = Array.from({ length: 10 }, (_, index) => event('pad', 2, .8, index * 150)); expect(run({ type: 'repeat', n: 8, withinMs: 4000 }, events).done).toBe(true) })
  it('repeat rejects uneven intervals', () => { const intervals = [120, 300, 140, 90, 260, 110, 320]; let ts = 0; const events = intervals.reduce((acc: LessonEvent[], gap, index) => { ts += index === 0 ? 0 : gap; acc.push(event('pad', 2, .8, ts)); return acc }, [event('pad', 2, .8, 0)]); expect(run({ type: 'repeat', n: 8, withinMs: 4000 }, events).done).toBe(false) })
  it('repeat ignores stray hits on other pads', () => { const steady = Array.from({ length: 10 }, (_, index) => event('pad', 2, .8, index * 150)); const strays = [event('pad', 0, .8, 75), event('pad', 0, .8, 675), event('pad', 0, .8, 1275)]; const events = [...steady, ...strays].sort((a, b) => a.ts - b.ts); expect(run({ type: 'repeat', n: 8, withinMs: 4000 }, events).done).toBe(true) })
  it('repeat denser requires a later window at least 1.6x faster and records the baseline', () => { const baseline = Array.from({ length: 10 }, (_, index) => event('pad', 2, .8, index * 200)); const faster = Array.from({ length: 20 }, (_, index) => event('pad', 2, .8, 4000 + index * 100)); const result = run({ type: 'repeat', n: 8, withinMs: 4000, denser: true }, [...baseline, ...faster]); expect(result.done).toBe(true); expect(result.state.baselineMedian).toBe(200) })

  it('dynamics recognizes wide velocity contrast', () => { const velocities = [.2, .9, .3, .8, .25, .85]; const events = velocities.map((v, index) => event('pad', 0, v, index * 100)); expect(run({ type: 'dynamics', kind: 'pad', minHits: 6, spread: .35 }, events).done).toBe(true) })
  it('dynamics rejects flat velocities', () => { const velocities = [.78, .80, .79, .81, .77, .80]; const events = velocities.map((v, index) => event('pad', 0, v, index * 100)); expect(run({ type: 'dynamics', kind: 'pad', minHits: 6, spread: .35 }, events).done).toBe(false) })
  it('dynamics reports blended progress from hits and spread', () => { const velocities = [.2, .85, .25, .9]; const events = velocities.map((v, index) => event('pad', 0, v, index * 100)); const result = run({ type: 'dynamics', kind: 'pad', minHits: 6, spread: .35 }, events); expect(result.done).toBe(false); expect(result.progress).toBeCloseTo(2 / 3) })

  it('groovemix recognizes a steady stream pad plus scattered other hits', () => { const stream = Array.from({ length: 10 }, (_, index) => event('pad', 2, .8, index * 150)); const others = [event('pad', 0, .8, 75), event('pad', 0, .8, 375), event('pad', 0, .8, 675), event('pad', 0, .8, 975)]; const events = [...stream, ...others].sort((a, b) => a.ts - b.ts); expect(run({ type: 'groovemix', streamN: 8, otherHits: 4, withinMs: 8000 }, events).done).toBe(true) })
  it('groovemix is half done with only the stream pad', () => { const stream = Array.from({ length: 10 }, (_, index) => event('pad', 2, .8, index * 150)); const result = run({ type: 'groovemix', streamN: 8, otherHits: 4, withinMs: 8000 }, stream); expect(result.done).toBe(false); expect(result.progress).toBe(.5) })
  it('groovemix rejects an unsteady stream pad even with other hits', () => { const gaps = [80, 400, 90, 380, 100, 420, 95]; let ts = 0; const stream = gaps.reduce((acc: LessonEvent[], gap, index) => { ts += index === 0 ? 0 : gap; acc.push(event('pad', 2, .8, ts)); return acc }, [event('pad', 2, .8, 0)]); const others = [event('pad', 0, .8, ts + 50), event('pad', 0, .8, ts + 150), event('pad', 0, .8, ts + 250), event('pad', 0, .8, ts + 350)]; expect(run({ type: 'groovemix', streamN: 8, otherHits: 4, withinMs: 8000 }, [...stream, ...others]).done).toBe(false) })

  it('contour recognizes a mostly rising line by direction and range', () => { const notes = [60, 62, 61, 64, 65, 67]; expect(run({ type: 'contour', minNotes: 6, minSpan: 5, withinMs: 8000, direction: 'up' }, noteStream(notes, 250)).done).toBe(true) })
  it('contour rejects the opposite direction', () => { const notes = [67, 65, 64, 62, 61, 60]; expect(run({ type: 'contour', minNotes: 6, minSpan: 5, withinMs: 8000, direction: 'up' }, noteStream(notes, 250)).done).toBe(false) })
  it('contour recognizes a line with a turn', () => { const notes = [60, 62, 64, 67, 65, 64, 62, 60, 59]; expect(run({ type: 'contour', minNotes: 9, minSpan: 7, withinMs: 10000, minTurns: 1 }, noteStream(notes, 250)).done).toBe(true) })

  it('phrases recognizes two note groups separated by a relative gap', () => { const first = noteStream([60, 62, 64, 65], 100); const second = noteStream([67, 65, 64, 62], 100, 1000); expect(run({ type: 'phrases', kind: 'key', minPhrases: 2, notesPerPhrase: 4, gapMs: 650, withinMs: 14000 }, [...first, ...second]).done).toBe(true) })
  it('phrases does not count one continuous run twice', () => { expect(run({ type: 'phrases', kind: 'key', minPhrases: 2, notesPerPhrase: 4, gapMs: 650, withinMs: 14000 }, noteStream([60, 62, 64, 65, 67, 69, 71, 72], 100)).done).toBe(false) })
  it('phrases scales its breath to the player, so a deliberate slow line still counts', () => { const goal: GoalSpec = { type: 'phrases', kind: 'key', minPhrases: 2, notesPerPhrase: 4, gapMs: 650, withinMs: 14000 }; const first = noteStream([60, 62, 64, 65], 800); const second = noteStream([67, 65, 64, 62], 800, 4400); expect(run(goal, [...first, ...second]).done).toBe(true) })
  it('phrases rejects an evenly slow run that never breathes', () => { expect(run({ type: 'phrases', kind: 'key', minPhrases: 2, notesPerPhrase: 4, gapMs: 650, withinMs: 14000 }, noteStream([60, 62, 64, 65, 67, 69, 71, 72], 800)).done).toBe(false) })

  it('alternation recognizes a changing two-pad stream', () => { const events = Array.from({ length: 12 }, (_, index) => event('pad', index % 2, .8, index * 150)); expect(run({ type: 'alternation', minHits: 12, minUnique: 2, changeRatio: .8, withinMs: 8000 }, events).done).toBe(true) })
  it('alternation rejects camping on one pad', () => { const events = Array.from({ length: 12 }, (_, index) => event('pad', index < 2 ? index : 0, .8, index * 150)); expect(run({ type: 'alternation', minHits: 12, minUnique: 2, changeRatio: .8, withinMs: 8000 }, events).done).toBe(false) })
  it('variety requires both enough hits and enough distinct controls', () => { const events = [0, 1, 2, 3, 0, 1, 2, 3].map((index, position) => event('pad', index, .8, position * 120)); expect(run({ type: 'variety', kind: 'pad', minHits: 8, minUnique: 4, withinMs: 6000 }, events).done).toBe(true); expect(run({ type: 'variety', kind: 'pad', minHits: 8, minUnique: 4, withinMs: 6000 }, events.map((item) => ({ ...item, index: item.index % 2 }))).done).toBe(false) })

  it('density recognizes a later section at least 1.6x faster', () => { const slow = [0, 400, 800, 1200].map((ts) => event('pad', 0, .8, ts)); const fast = [1300, 1400, 1500, 1600].map((ts) => event('pad', 1, .8, ts)); const result = run({ type: 'density', kind: 'pad', minHits: 4, ratio: 1.6, withinMs: 10000 }, [...slow, ...fast]); expect(result.state.baselineMedian).toBe(400); expect(result.done).toBe(true) })
  it('density does not complete from one unchanging pulse', () => { const events = Array.from({ length: 10 }, (_, index) => event('pad', 0, .8, index * 300)); expect(run({ type: 'density', kind: 'pad', minHits: 4, ratio: 1.6, withinMs: 10000 }, events).done).toBe(false) })
  it('density re-baselines when a later pulse is slower, so an eager fast start still recovers', () => { const goal: GoalSpec = { type: 'density', kind: 'pad', minHits: 4, ratio: 1.6, withinMs: 10000 }; const eager = [0, 100, 200, 300].map((ts) => event('pad', 0, .8, ts)); const roomy = [2000, 2500, 3000, 3500].map((ts) => event('pad', 0, .8, ts)); const burst = [3700, 3800, 3900, 4000, 4100, 4200].map((ts) => event('pad', 0, .8, ts)); const result = run(goal, [...eager, ...roomy, ...burst]); expect(result.state.baselineMedian).toBe(500); expect(result.done).toBe(true) })

  it('controlrange measures relative wheel travel', () => { const goal: GoalSpec = { type: 'controlrange', kind: 'pitch', span: .3 }; expect(run(goal, [event('pitch', 0, .5), event('pitch', 0, .76)]).done).toBe(false); expect(run(goal, [event('pitch', 0, .5), event('pitch', 0, .82)]).done).toBe(true) })
  it('mix recognizes keys, pads, and moved knobs inside one window', () => { const controls = [event('key', 60, .7, 0), event('key', 64, .7, 100), event('key', 67, .7, 200), event('pad', 0, .7, 300), event('pad', 1, .7, 400), event('knob', 2, .1, 500), event('knob', 2, .5, 600)]; expect(run({ type: 'mix', withinMs: 2000, keys: 3, pads: 2, knobs: 1, keySpan: 5, controlSpan: .3 }, controls).done).toBe(true) })
  it('mix requires each requested wheel to travel', () => { const controls = [event('key', 60, .7, 0), event('key', 62, .7, 100), event('pitch', 0, .5, 200), event('pitch', 0, .8, 300), event('mod', 0, .1, 400), event('mod', 0, .45, 500)]; expect(run({ type: 'mix', withinMs: 2000, keys: 2, pitch: true, mod: true, controlSpan: .25 }, controls).done).toBe(true); expect(run({ type: 'mix', withinMs: 2000, keys: 2, pitch: true, mod: true, controlSpan: .25 }, controls.slice(0, 4)).done).toBe(false) })

  it('confirm never completes from events', () => { expect(run({ type: 'confirm' }, [event('key', 60)]).done).toBe(false) })

  it('contour rejects padding with repeated notes but recognizes a genuine line', () => { const goal: GoalSpec = { type: 'contour', minNotes: 6, minSpan: 5, withinMs: 8000, direction: 'up' }; expect(run(goal, noteStream([60, 60, 60, 60, 60, 65], 400)).done).toBe(false); expect(run(goal, noteStream([60, 62, 61, 64, 65, 67], 250)).done).toBe(true) })
  it('stream denser recovers even after an already-fast baseline', () => { const goal: GoalSpec = { type: 'stream', n: 10, withinMs: 3000, denser: true }; const baseline = noteStream(Array.from({ length: 12 }, (_, index) => 60 + index % 3 * 4), 125); const faster = noteStream(Array.from({ length: 24 }, (_, index) => 60 + index % 3 * 4), 62, 3200); expect(run(goal, [...baseline, ...faster]).done).toBe(true) })
  it('mix requires distinct knobs, not one knob swept twice', () => { const goal: GoalSpec = { type: 'mix', withinMs: 2000, knobs: 2 }; const oneKnobTwice = [event('knob', 0, .1, 0), event('knob', 0, .9, 100), event('knob', 0, .1, 200), event('knob', 0, .9, 300)]; expect(run(goal, oneKnobTwice).done).toBe(false); const twoKnobs = [event('knob', 0, .1, 0), event('knob', 0, .9, 100), event('knob', 1, .1, 200), event('knob', 1, .9, 300)]; expect(run(goal, twoKnobs).done).toBe(true) })
  it('mix progress can decrease as events age out of the window', () => { const goal: GoalSpec = { type: 'mix', withinMs: 1000, keys: 2, pads: 4 }; const events = [event('key', 60, .8, 0), event('key', 62, .8, 100), event('pad', 0, .8, 200), event('pad', 1, .8, 300), event('pad', 2, .8, 1300)]; const beforeAging = run(goal, events.slice(0, 4)); const afterAging = run(goal, events); expect(beforeAging.progress).toBeCloseTo(.5); expect(afterAging.progress).toBeLessThan(beforeAging.progress); expect(afterAging.done).toBe(false) })
  it('phrases works on kind: pad, not just keys', () => { const goal: GoalSpec = { type: 'phrases', kind: 'pad', minPhrases: 2, notesPerPhrase: 4, gapMs: 650, withinMs: 14000 }; const first = Array.from({ length: 4 }, (_, index) => event('pad', index, .8, index * 100)); const second = Array.from({ length: 4 }, (_, index) => event('pad', index, .8, 1000 + index * 100)); expect(run(goal, [...first, ...second]).done).toBe(true) })
})
